### ISSUE TITLE
JARs built will not run with Homebrew OpenJDK on macOS Sonoma

### ISSUE THREAD

**Issue by rarecoil** [rarecoil/gaia-tool#1]
JARs built with `mvn verify` in the traditional way do not execute when using Homebrew OpenJDK. An attempt to load CMenuItem will crash the application.

This is a known issue in other applications such as visualvm - https://github.com/oracle/visualvm/issues/528 and that group believes it's a Homebrew JDK problem.

From the stack trace:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000018790161c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [36848]

Application Specific Information:
References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.
```

Love it when Apple links to internal bugs.

**Comment by jourquin** [comment]
The problem seems to appear for any java app that uses the native macOS "Screen menu bars" setting
```
System.setProperty("apple.laf.useScreenMenuBar", "true");
```
This affects macOS Sonoma systems with a Homebrew OpenJDK. 

A quick and dirty fix (in the java code) is to avoid setting this property on affected systems. A example can be found at the end of the following code :
https://github.com/jourquin/Nodus/blob/master/src/edu/uclouvain/core/nodus/Nodus.java

The test is used in line 253.

Obviously, the menu bar will be in the main application window, and not on the top of the screen, which is not a standard behavior for macOS applications.

**Comment by rarecoil** [comment]
@jourquin Thanks for providing a workaround for now; I've patched this code and am closing the issue. This tool is from 2010 and I'm just trying to preserve it for future use, so whether or not it uses the macOS system menubar is irrelevant for keeping it functional.
